name: Edel
favicon: null
layout_spectrum: 0.5333213000558317
typography_spectrum: 0.6528793638572097
title: Diary Of A Gourmande
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5335980076342821
  lightness: 0.7098671798594296
  saturation: 0.8166877483017743
  rhythmicContrast: 0.9520672031212598
purpose: []
